apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: interinvestapi-deployment
  name: interinvestapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interinvestapi
  template:
    metadata:
      labels:
        app: interinvestapi
    spec:
      containers:
      - env:
        - name: APP_ENV
          value: dev
        - name: TZ
          value: Europe/Paris
        image: nginx#interinvestcontainersregistry.azurecr.io/interinvest/api:20854
        name: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: interinvestapi
  name: interinvestapi-service
spec:
  ports:
  - port: 80
  selector:
    app: interinvestapi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: interinvestapi-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: api.inter-invest.local
    http:
      paths:
      - backend:
          service:
            name: interinvestapi-service
            port:
              number: 80
        path: /
        pathType: Prefix
